// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-playground/validator"
	"github.com/google/wire"
	"golang-dependency-injection/app"
	"golang-dependency-injection/controllers"
	"golang-dependency-injection/middlewares"
	"golang-dependency-injection/repositories"
	"golang-dependency-injection/services"
	"net/http"
)

// Injectors from injector.go:

func InitializeServer() *http.Server {
	categoryRepositoryContract := repositories.NewCategoryRepository()
	db := app.NewDB()
	validate := validator.New()
	categoryServiceContract := services.NewCategoryService(categoryRepositoryContract, db, validate)
	controllerContract := controllers.NewCategoryController(categoryServiceContract)
	router := app.NewCategoryRouter(controllerContract)
	authMiddleware := middlewares.NewAuthMiddleware(router)
	server := app.NewServer(authMiddleware)
	return server
}

// injector.go:

var categorySet = wire.NewSet(repositories.NewCategoryRepository, services.NewCategoryService, controllers.NewCategoryController)
